// generar api
const apiEvamed = 'http://localhost:8000/api-projects',
// apis
 projects = '/projects/',
 transports = '/transports/',
 uses = '/uses/',
 countries = '/countries/',
 typeProject = '/type-project/',
 usefulLife = '/useful-life/',
 housingScheme = '/housing-scheme/',
 materials = '/materials/',
 sourceInformation = '/source-information/',
 bulkUnits = '/bulk-units/',
 energyUnits = '/energy-units/',
 volumeUnits = '/volume-units/',
 schemeProject = '/material-scheme-project/',
 schemeProjectOriginal = '/material-scheme-project-original/',
 constructionStage = '/constructive-system-element/',
 annualConsumptionRequired = '/annual-consumption-required/',
 typeEnergy = '/type-energy/',
 electricityConsumptionData = '/electricity-consumption-data/',
 treatmentOfGenerateWasted = '/treatment-of-generate-wasted/',
 electricityConsumptionDeconstructiveProcess =
  '/electricity-consumption-deconstructive-process/',
 materialSchemeData = '/material-scheme-data/',
 materialsStage = '/materials-stage/',
 materialsStageUpdate = '/materials-stage/update/',
 potentialTypes = '/potential-types/',
 standards = '/standards/',
 sourceInformationData = '/source-information-data/',
 typeEnergyData = '/type-energy-data/',
 users = '/users-platform/',
 states = '/states/',
 cities = '/cities/',
 localDistances = '/local-distances/',
 externalDistance = '/external-distance/',
 sections = '/sections/',
 units = '/units/',
 potentialTranposrt = '/potential-transport/',
 conversion = '/conversions/',
 dbMaterial = '/database-material/';

export const environment = {
  production: false,
  api_projects: `${apiEvamed}${projects}`,
  api_transports: `${apiEvamed}${transports}`,
  api_uses: `${apiEvamed}${uses}`,
  api_countries: `${apiEvamed}${countries}`,
  api_type_project: `${apiEvamed}${typeProject}`,
  api_useful_life: `${apiEvamed}${usefulLife}`,
  api_housing_scheme: `${apiEvamed}${housingScheme}`,
  api_materials: `${apiEvamed}${materials}`,
  api_source_information: `${apiEvamed}${sourceInformation}`,
  api_bulk_units: `${apiEvamed}${bulkUnits}`,
  api_energy_units: `${apiEvamed}${energyUnits}`,
  api_volume_units: `${apiEvamed}${volumeUnits}`,
  api_scheme_project: `${apiEvamed}${schemeProject}`,
  api_scheme_project_original: `${apiEvamed}${schemeProjectOriginal}`,
  api_construction_stage: `${apiEvamed}${constructionStage}`,
  api_annual_consumption_required: `${apiEvamed}${annualConsumptionRequired}`,
  api_type_energy: `${apiEvamed}${typeEnergy}`,
  api_electricity_consumption_data: `${apiEvamed}${electricityConsumptionData}`,
  api_treatment_of_generate_wasted: `${apiEvamed}${treatmentOfGenerateWasted}`,
  api_electricity_consumption_deconstructive_process: `${apiEvamed}${electricityConsumptionDeconstructiveProcess}`,
  api_material_scheme_data: `${apiEvamed}${materialSchemeData}`,
  api_materials_stage: `${apiEvamed}${materialsStage}`,
  api_materials_stage_update: `${apiEvamed}${materialsStageUpdate}`,
  api_potetnial_types: `${apiEvamed}${potentialTypes}`,
  api_standards: `${apiEvamed}${standards}`,
  api_source_information_data: `${apiEvamed}${sourceInformationData}`,
  api_type_energy_data: `${apiEvamed}${typeEnergyData}`,
  api_users: `${apiEvamed}${users}`,
  api_states: `${apiEvamed}${states}`,
  api_cities: `${apiEvamed}${cities}`,
  api_local_distances: `${apiEvamed}${localDistances}`,
  api_exterternal_distances: `${apiEvamed}${externalDistance}`,
  api_sections: `${apiEvamed}${sections}`,
  api_units: `${apiEvamed}${units}`,
  api_potential_transport: `${apiEvamed}${potentialTranposrt}`,
  api_conversions: `${apiEvamed}${conversion}`,
  api_db_material: `${apiEvamed}${dbMaterial}`,
  firebaseConfig: {
    apiKey: "AIzaSyC3t_NpPrGwj7i26j5cfIQCt1aaq3f9k-I",
    authDomain: "evamed-ac3f8.firebaseapp.com",
    projectId: "evamed-ac3f8",
    storageBucket: "evamed-ac3f8.firebasestorage.app",
    messagingSenderId: "511289930174",
    appId: "1:511289930174:web:25abc474c59e76ae3e89ef",
    measurementId: "G-DXRYB3RM3H",
  },
};
