# Generated by Django 2.2 on 2026-03-02 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0076_auto_20220322_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialStageSystemSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction_system', models.CharField(max_length=255)),
                ('is_selected', models.BooleanField(default=True)),
                ('origin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_api.Origin')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_api.Project')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_api.Section')),
            ],
        ),
        migrations.AddConstraint(
            model_name='materialstagesystemselection',
            constraint=models.UniqueConstraint(fields=('project_id', 'section_id', 'origin_id', 'construction_system'), name='uniq_material_stage_system_selection'),
        ),
    ]
