# Generated by Django 2.2 on 2026-09-04 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0078_userplatform_email_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='ecoinvent_dataset_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='ecoinvent_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='ecoinvent_system_model',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='ecoinvent_version',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='sourceinformation',
            name='ecoinvent_dataset_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sourceinformation',
            name='ecoinvent_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourceinformation',
            name='ecoinvent_system_model',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='sourceinformation',
            name='ecoinvent_version',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='ecoinvent_dataset_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='ecoinvent_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='ecoinvent_system_model',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='ecoinvent_version',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='typeenergy',
            name='ecoinvent_dataset_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='typeenergy',
            name='ecoinvent_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typeenergy',
            name='ecoinvent_system_model',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='typeenergy',
            name='ecoinvent_version',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='EcoinventIndicatorMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_id', models.IntegerField()),
                ('method_name', models.CharField(max_length=255)),
                ('indicator_name', models.CharField(max_length=255)),
                ('expected_unit', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('potential_type_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects_api.PotentialType')),
                ('unit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects_api.Unit')),
            ],
        ),
    ]
