# Generated by Django 2.2 on 2026-09-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0081_ecoinvent_unit_realignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoinventUsageReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_ids', models.TextField()),
                ('indicator_ids', models.TextField()),
                ('reason', models.CharField(default='refresh', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
