# Generated by Django 4.2.30 on 2026-09-11 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0083_remove_userplatform_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localdistance',
            name='city_id_end',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to='projects_api.city'),
        ),
        migrations.AlterField(
            model_name='materialschemeproject',
            name='city_id_end',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to='projects_api.city'),
        ),
        migrations.AlterField(
            model_name='materialschemeproject',
            name='transport_id_end',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created_second', to='projects_api.transport'),
        ),
        migrations.AlterField(
            model_name='materialschemeprojectorigianal',
            name='city_id_end',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to='projects_api.city'),
        ),
        migrations.AlterField(
            model_name='materialschemeprojectorigianal',
            name='transport_id_end',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created_second', to='projects_api.transport'),
        ),
    ]
